### ISSUE TITLE
Create "All Tags" button and functionality for homepage

### ISSUE THREAD

**Issue by moranw** [yarindeoh/safe-home-haytiSham#105]
As seen on the homepage on Figma - 
When first loading the page - this button should be selected, meaning the first page of stories should be loaded (getStoriesByTags can get no tags and then it returns all)

**Comment by hadasfarhi** [comment]
@yarindeoh @moranw 
I implemented the changes we agreed on at Monday's meeting.
I wanted to draw your attention to the problem - when someone clicks on "all tags," the stories list displays stories written for testing purposes that are not linked to any tag. 
Is the development database is also intended for production usage? If it is, maybe it will be better to delete the fictive stories.
