### ISSUE TITLE
Fix story page UI according to figma

### ISSUE THREAD

**Issue by moranw** [yarindeoh/safe-home-haytiSham#107]
*The fields should be ordered the same as it appears on figma
*Should fix css according to figma (margins on the side, header colors)
*remove old buttons for help and share bellow + include new 24/7 button
*it should include other relevant stories according to the current story. Selected stories have 3 first tags from the current story (OR logic). --> no tags filtering or selection will be possible from an inner page, it just shows "similar stories" that have similar tags (Lishay will provide updated UI for this part)

**Comment by rotem12345678** [comment]
@moranw 
1. Where to locate "מה עזר לך להתמודד?", it is not in Figma...
2. What do you mean by: "remove old buttons for help and share bellow"? 
You can see what I changed in branch: rotem_story_page_UI_according_to_figma
