### ISSUE TITLE
Texts fixes - Final texts from Noa TBD

### ISSUE THREAD

**Issue by moranw** [yarindeoh/safe-home-haytiSham#238]
1. testimony page -> add a '*' sign for mandatory question - missing in background field
2. testimony page -> remove the part about getting back to you
3. testimony page -> after finishing the testimony -> change the text - if it's not uploaded they can contact us
4. admin page -> remove the getting back at them on instructions
5. admin page -> remove the getting back at them from popup
6. admin page -> add mandatory '*' sign for tags selection
7. admin page -> add mandatory '*' sign for quote

**Comment by rotem12345678** [comment]
add contact text 
add link to "לקבלת תנאי שימוש"
