### ISSUE TITLE
Create moderate page -  basic stories editor 

### ISSUE THREAD

**Issue by yarindeoh** [yarindeoh/safe-home-haytiSham#26]
Will be hosted on a different route after successful login. See #89 

Route should be: "/admin"
Functionality flow here (UI TBD): https://docs.google.com/presentation/d/14BQr1OpmMxczdlmjFBKiaXpp_o_n05qjzsfwA3cszcA/edit#slide=id.g90e0026188_0_48

**Comment by moranw** [comment]
Functionality scheme for moderation flow - https://docs.google.com/presentation/d/14BQr1OpmMxczdlmjFBKiaXpp_o_n05qjzsfwA3cszcA/edit?usp=sharing
