### ISSUE TITLE
Send automatic email to admin "haytisham@gmail.com" after calling addStory from the api

### ISSUE THREAD

**Issue by moranw** [yarindeoh/safe-home-haytiSham#39]
Subject: התקבלה עדות חדשה באתר
Body: היי! קיבלנו עדות חדשה שממתינה למודרציה לפני העלאה לאתר. אנא היכנסו אל <admin url> וערכו את העדות וערכו אותה כדי שתעלה אל האתר.

**Comment by Lealea8455** [comment]
@moranw 
Hi Moran,
I need a password for haytisham@gmail.com to be able to send an automatic e-mail. 
Please send me via Slack/Facebook or another preferred way.

**Comment by orlylev** [comment]
We need to select email service to implement

**Comment by yarindeoh** [comment]
@orlylev check this PR:
https://github.com/yarindeoh/safe-home-haytiSham/pull/147/commits/0fb62ebc6dfe14c87ef053e92a369868c288f8d5

**Comment by moranw** [comment]
Hey @Lealea8455 what's the status here?

**Comment by Lealea8455** [comment]
@moranw 
Hi, 
The task is done a long time ago, still waiting for review, didn't want to push before.
