### ISSUE TITLE
Basic login flow

### ISSUE THREAD

**Issue by yarindeoh** [yarindeoh/safe-home-haytiSham#89]
With static creds (of haytiSham mail). Create a separate route implement functionality 

Route should be:  "/admin"
Functionality flow here (UI TBD): https://docs.google.com/presentation/d/14BQr1OpmMxczdlmjFBKiaXpp_o_n05qjzsfwA3cszcA/edit#slide=id.g90e0026188_0_48

**Comment by moranw** [comment]
Functionality flow for admin view (login + moderations: https://docs.google.com/presentation/d/14BQr1OpmMxczdlmjFBKiaXpp_o_n05qjzsfwA3cszcA/edit?usp=sharing)
